[package]
edition = "2021"
name = "rucaptcha"
version = "3.0.0"

[[bin]]
bench = false
path = "src/captcha.rs"
name = "captcha"

[dependencies]
image = "0.24.4"
imageproc = "0.23.0"
rand = "0.8.5"
rusttype = "0.9.2"
